### ISSUE TITLE
Questionable for-loop variable

### ISSUE THREAD

**Issue by maucon** [TheSwerik/CalcPrimesMultiThread#5]
CalcPrimesMultiThread/Backend/src/Prime/Task/StaticPrime.cs 
Starting at line 29
```
for (long i = 3; i <= root && !(token?.IsCancellationRequested ?? false); i += 2)
   if (!sieve[i])
   {
      primes.Add((int) i);
      var add = i << 1;
      for (var j = i * i; j <= n; j += add) sieve[j] = true;
   }
```
Why is the first for-loop used with a long, which gets cast to an int later on?

**Comment by TheSwerik** [comment]
i think it was overflowing thats why but i dont really remember

**Comment by TheSwerik** [comment]
yeah pretty sure it overflowes at `var add = i << 1` so wont change that
